# Generated by Django 6.0.6 on 2026-06-03 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('course_rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('slope_rating', models.IntegerField()),
                ('date_played', models.DateField()),
                ('weather', models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('windy', 'Windy'), ('rainy', 'Rainy')], max_length=20, null=True)),
                ('wind_strength', models.CharField(blank=True, choices=[('none', 'None'), ('light', 'Light'), ('moderate', 'Moderate'), ('strong', 'Strong')], max_length=20, null=True)),
                ('green_speed', models.CharField(blank=True, choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], max_length=20, null=True)),
                ('green_firmness', models.CharField(blank=True, choices=[('soft', 'Soft'), ('normal', 'Normal'), ('firm', 'Firm')], max_length=20, null=True)),
                ('fairway_conditions', models.CharField(blank=True, choices=[('wet', 'Wet'), ('normal', 'Normal'), ('dry', 'Dry'), ('firm', 'Firm')], max_length=20, null=True)),
                ('miss_category', models.CharField(blank=True, choices=[('driving', 'Driving'), ('iron_play', 'Iron Play'), ('chipping', 'Chipping'), ('putting', 'Putting'), ('bunker', 'Bunker')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
    ]
